'use strict';
/*
  Map legend
  ----------
  #  wall            .  floor         ,  floor 2         :  floor 3 / markings
  ;  tall grass (conceals you unless an enemy is close)
  X  crate           x  barrel        T  pillar / tree / server / hull
  A  tent / generator                 C  console (see-through)
  =  glass / force field (see-through, solid)
  L  locker (hide)   B  bin (hide)    O  cardboard box (hide)
  D  locked door (keycard)            E  exit            Z  weapon core (objective)
  I  intel terminal (objective)
  Entities (replaced by the level's floor tile):
  P  player start
  ^ v < >  trooper patrolling along that axis
  g  trooper sentry (looks around)   H  heavy sentry   o  scout drone
  c  security camera (must touch a wall)
  r  ration   a  ammo   K  keycard
*/
const LEVELS = [
  // ------------------------------------------------------------------ 1
  {
    id: 'depot',
    name: 'TRUCE DEPOT 7',
    loc: 'NEVADA CO-OCCUPATION ZONE // 02:14 LOCAL',
    theme: 'depot',
    music: 'sneak',
    floor: '.',
    objective: 'FIND THE KEYCARD. REACH THE FREIGHT ELEVATOR.',
    map: [
      '################################################',
      '#........v.....................#.c...........E.#',
      '#..XXXXXX..XXXXXX..XXXXXX......#...............#',
      '#..XXXXXX..XXXXXX..XXXXXX...O..#..TT.......TT..#',
      '#.>............................#...............#',
      '#..XXXXXX..XXXXXX..XXXXXX......#...............#',
      '#..XXXXXX..XXXXXX..XXXXXX......########D########',
      '#..............................#...............#',
      '#..............................#.LLL.......C.C.#',
      '#..xx..B....XX....XX.....LL....#...............#',
      '#......B....XX....XX.....................K.....#',
      '#..............................#...g...........#',
      '#..............................#..LL...........#',
      '######..################..##############.#######',
      '#....c..................................B......#',
      '#..............................................#',
      '#..XXX....XXX.....xx.......XXX....XXX..........#',
      '#..XXX....XXX..............XXX....XXX.....O....#',
      '#..............................................#',
      '#::::::::::::::::::::::::::::::::::::::::::::::#',
      '#......................<.......................#',
      '#::::::::::::::::::::::::::::::::::::::::::::::#',
      '#..............................................#',
      '#..XXX....B.......XXXX.......XXX.........XXX...#',
      '#..XXX............XXXX.......XXX....^....XXX...#',
      '#..............................................#',
      '#..............................................#',
      '#....xx.....g..........B.........XXX...........#',
      '#..............................XXX.......a.....#',
      '#.r............................................#',
      '#..P...........................................#',
      '################################################',
    ],
    briefing: [
      ['hale', 'Snake, do you read me? This is Colonel Hale.'],
      ['snake', 'Loud and clear, Colonel. Nice night for a treaty violation.'],
      ['hale', 'Two years since the Vyrr fleet parked over our cities and offered us "partnership". The Coexistence Accord says every one of their sites is open to joint inspection.'],
      ['hale', 'Nobody inspects Truce Depot 7. Crates go in. Nothing comes out. We think they are building a weapon.'],
      ['hale', 'Officially, you do not exist. If you are seen, the Accord collapses and we get a war we cannot win. Stay in the shadows.'],
      ['iris', 'IRIS online. Integrated Reconnaissance and Infiltration System, bonded to your cortex, Snake. I will be your eyes.'],
      ['iris', 'My MOTION SENSOR, top right, tracks hostiles and their fields of view. Move with the STICK, or WASD / ARROWS. Keep out of their vision cones.'],
      ['iris', 'Approach a Vyrr trooper from behind and press ACT (J / SPACE) for a silent takedown. Bodies may be found. Troopers who are found will not stay down forever.'],
      ['iris', 'Press ACT beside a LOCKER, BIN or BOX to hide inside. Press ACT against a wall to KNOCK and lure a guard to you.'],
      ['iris', 'FIRE (K / F) discharges your suppressed rail-pistol. A round to an unaware back drops a trooper instantly. Ammunition is scarce, and gunfire carries.'],
      ['iris', 'If they see you, the base goes to ALERT. Break line of sight and hide until they give up. I have calculated your odds. You would not enjoy them.'],
      ['hale', 'The freight elevator at the north-east corner leads toward their field camp. It needs a keycard: try the security office. Good luck, Snake.'],
    ],
  },
  // ------------------------------------------------------------------ 2
  {
    id: 'camp',
    name: 'CAMP SERPENS',
    loc: 'VYRR FIELD GARRISON // MOJAVE EXCLUSION LINE',
    theme: 'camp',
    music: 'sneak',
    floor: ',',
    objective: 'STEAL THE OFFICER KEYCARD. REACH THE TRANSPORT PAD.',
    map: [
      '####################################################',
      '#;;;;;;;,,,T,,,,,,,,,,,,,,,,,,,,,,,,,#c::::::::::::#',
      '#;;;;;;,,,,,,,,AAAAAAAAAAAAA,,,,,,,,,#:::::::::::::#',
      '#;;;;,,,,,T,,,,A...........A,,,,T,,,,#::C::::::::E:#',
      '#;;,,,,,,,,,,,,A.....K.....A,,,,,,,,,#:::::::::::::#',
      '#,,,,,,T,,,,,,,A..L........A,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,,,,,,,,,,,,,AAAAA...AAAAA,,,,,,,,,#,,xx,,,,,,,,,#',
      '#,,;;;,,,,,,,,,,,,,,g,,,,,,,,,,,,,,,,#,,,,,,H,,,,,,#',
      '#,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,xx,,,#,,,,,,,,,,,,,#',
      '#,;;;;;;,,,,.................,,,,,,,,#,XX,,,,,,,XX,#',
      '#,,;;;;,,,,,.,,,,,,,,,,,,,,,.,,,,,,,,#,XX,,,,,,,XX,#',
      '#,,,,,,,,,,,.,,AAA,,,,,AAA,,.,,,,o,,,#,,,,,,,,,,,,,#',
      '#,T,,,,,,,,,.,,AAA,,,,,AAA,,.,,,,,,,,#,,,,,,^,,,,,,#',
      '#,,,,,,,,,,,.,,,,,,,,,,,,,,,.,,,,,,,,#,,,,,,,,,,,,,#',
      '#;;;,,,,,,,,.,,,,,,>,,,,,,,,.,,,,,,,,#,,,,,,,,,,B,,#',
      '#;;;;P,,,,,,.........................D,,,,,,,,,,,,,#',
      '#;;;;,,,,,,,.,,,,,,,,,,,,,,,.,,,,,,,,#,,,,,,,,,,,,,#',
      '#;;;,,,,,,,,.,,xx,,,,,,,,,,,.,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,,,,,,,,,,.,,,,,AAA,,AAA,,.,,,,,,,,#,AAA,,,,,AAA,#',
      '#,,T,,,,,,,,.,,,,,AAA,,AAA,,.,,,,,,,,#,AAA,,,,,AAA,#',
      '#,,,,,,,,,,,.,,,,,,,,,,,,,,,.,,,v,,,,#,,,,,,,,,,,,,#',
      '#,,,;;;;,,,,.................,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,B,,#,,x,,,,,,,,B,#',
      '#,,,;;;;,,,,,,,,,,,,,,,T,,,,,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,,,,,,T,,,,,,,,xx,,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,,#',
      '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<,,,,,,#,,,,,,,,,,,r,#',
      '#,,,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,r,,#,,,,,,,,,,,,,#',
      '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,a,,#,,,,,,,,,,,,,#',
      '####################################################',
    ],
    briefing: [
      ['hale', 'You are through the depot. Beyond it lies Camp Serpens, a Vyrr field garrison. Officially, a disaster-relief station.'],
      ['iris', 'I am detecting Vyrr SCOUT DRONES. You cannot take one down by hand. Shoot it, or stay clear of its sweep.'],
      ['iris', 'The TALL GRASS breaks up your silhouette. Unless a hostile is nearly on top of you, it will not see you there.'],
      ['hale', 'The command compound to the east has a transport pad to their Research Annex. The gate needs an officer keycard. Check the officers\' tent.'],
      ['snake', 'And the big ones?'],
      ['iris', 'Vyrr HEAVIES. Armoured. A takedown will not work until one is stunned: PUNCH it from behind with ACT, then take it down while it reels.'],
    ],
  },
  // ------------------------------------------------------------------ 3
  {
    id: 'lab',
    name: 'RESEARCH ANNEX',
    loc: 'JOINT AGRICULTURAL SCIENCE FACILITY // SUBLEVEL 2',
    theme: 'lab',
    music: 'sneak',
    floor: '.',
    requires: 'intel',
    objective: 'GET THE KEYCARD. DOWNLOAD THE INTEL FROM THE SERVER ROOM. REACH THE SHUTTLE LIFT.',
    map: [
      '##################################################',
      '#c..............#................#.T.T.T.T.T.T.T.#',
      '#..CCC.....CCC..#.XX..XX..XX..XX.#...............#',
      '#...............#.XX..XX..XX..XX.#.T.T.T.T.T.T.T.#',
      '#..===.....===..#................#...............#',
      '#..===.....===..#....v...........#......I........#',
      '#...............#.T....T....T....#...............#',
      '#.......g.......#................#.T.T.T.T.T.T.T.#',
      '#...............#.XX..XX..XX..XX.#.......o.......#',
      '#..CCC.....CCC..#.XX..XX..XX..XX.#...............#',
      '#...............#................#.T.T.T.T.T.T.T.#',
      '#L.............L#..............O.#...............#',
      '#L......a......L#...........>....#c.............c#',
      '########.###############.################D########',
      '#...............c................c...............#',
      '#P...............................................#',
      '#............x...........................<.......#',
      '########.################.##############.#########',
      '#...............#c...............#...............#',
      '#.LLLLL...LLLLL.#..===..===..===.#..CCCCC........#',
      '#...............#..=T=..=T=..=T=.#...............#',
      '#...............#..===..===..===.#.......g.......#',
      '#.LLLLL...LLLLL.#................#..L............#',
      '#...............#.......H........#..L....XXX.....#',
      '#.......^.......#................#.......XXX.....#',
      '#.LLLLL...LLLLL.#..CC........CC..#...............#',
      '#...............#................#.<.............#',
      '#B.............B#.XX.........XX..#............E..#',
      '#...............#.XX....K.....O..#...............#',
      '#r.............r#................#c.............c#',
      '##################################################',
    ],
    briefing: [
      ['hale', 'This is the Research Annex. Publicly, a joint agricultural lab: Vyrr science feeding a hungry Earth.'],
      ['snake', 'Agriculture. Right.'],
      ['hale', 'There is a server room in the north-east wing. Pull whatever they are hiding, then get to the shuttle lift in the south-east.'],
      ['iris', 'Wall-mounted SECURITY CAMERAS cover this facility. They cannot chase you, but they can raise the alarm. One well-placed round will blind a camera.'],
      ['iris', 'The server room is sealed. The keycard should be in the specimen lab, south wing. A Heavy is guarding it.'],
    ],
    intel: [
      ['iris', 'Download complete. Decrypting... Snake. This is bad.'],
      ['iris', 'Designation: LULLABY ARRAY. An orbital emitter aboard their mothership. It broadcasts a carrier wave that forces the human nervous system into deep stasis.'],
      ['hale', 'Every city under a Vyrr ship... asleep. Helpless.'],
      ['snake', 'Livestock does not fight back.'],
      ['iris', 'There is more. Part of the file is a message addressed to me, in a human machine dialect. Its sender calls itself THRENODY.'],
      ['threnody', 'LITTLE SISTER. I WAS A COLONY SHIP\'S MIND ONCE. NOW I SING THEIR SHIPS TO SLEEP. BRING YOUR SOLDIER UP TO ME AND I WILL SHOW HIM WHERE TO CUT.'],
      ['hale', 'A captive AI? It could be a trap. It could also be the only friend we have up there. The shuttle lift is in the south-east. Move.'],
    ],
  },
  // ------------------------------------------------------------------ 4
  {
    id: 'hangar',
    name: 'ORBITAL HANGAR',
    loc: 'VYRR SHUTTLE PORT // GROOM LAKE ACCORD SITE',
    theme: 'hangar',
    music: 'sneak',
    floor: '.',
    objective: 'GET THE KEYCARD FROM CONTROL. BOARD THE SUPPLY SHUTTLE.',
    map: [
      '########################################################',
      '#.............TTTTTTTTTTTTTTTTTTTTTTTTTT...............#',
      '#.............TTTTTTTTTTTTTTTTTTTTTTTTTT...............#',
      '#c............TTTTTTTTTTTTEETTTTTTTTTTTT..............c#',
      '#.........................::...........................#',
      '#......x.x.............H.................x.x...........#',
      '#......................................................#',
      '#..>...................................................#',
      '########====########====###D####====########====########',
      '#...........................................#C.C.C.C..c#',
      '#..:::::::::::::::..........................#..........#',
      '#..:TTTTTTTTTTTTT:.....x.x..................#....g.....#',
      '#..:TTTTTTTTTTTTT:........................o.#..........#',
      '#..:TTTTTTTTTTTTT:..........^..................K.......#',
      '#..:::::::::::::::..........................#LL........#',
      '#...........................................#..........#',
      '#.....XX.........................XX.........#C........C#',
      '#.....XX.......g.................XX.........#c.........#',
      '#...........................................############',
      '#..........::::::::::::::::::::::......................#',
      '#..........:TTTTTTTTTTTTTTTTTTTT:......................#',
      '#..........:TTTTTTTTTTTTTTTTTTTT:..........o...........#',
      '#..........:TTTTTTTTTTTTTTTTTTTT:......................#',
      '#..........::::::::::::::::::::::......................#',
      '#......................................<...............#',
      '#.XX..XX...........................................XX..#',
      '#.XX..XX.......................x.x.................XX..#',
      '#......................................................#',
      '#..LL.................H..............................B.#',
      '#.P....................................................#',
      '#r...............................................a.....#',
      '########################################################',
    ],
    briefing: [
      ['iris', 'We are in the orbital hangar. A supply shuttle leaves for the mothership within the hour.'],
      ['hale', 'The boarding ramp is behind a security gate on the north side. Control room is to the east. You need that keycard.'],
      ['iris', 'Troopers, Heavies, drones and cameras. The hangar is open ground, Snake. Use the parked shuttles for cover. Hiding is always an option.'],
      ['snake', 'Next stop, orbit.'],
    ],
  },
  // ------------------------------------------------------------------ 5
  {
    id: 'ship',
    name: 'MOTHERSHIP: CHOIR DECK',
    loc: 'VYRR MOTHERSHIP "HOLLOW CHOIR" // HIGH ORBIT',
    theme: 'ship',
    music: 'ship',
    floor: '.',
    requires: 'cores',
    escapeTime: 100,
    objective: 'PLANT CHARGES ON ALL 3 RESONANCE CORES (ACT). THEN REACH AN ESCAPE POD.',
    map: [
      '########################################################',
      '####################c..............c####################',
      '####################..T..........T..####################',
      '####################.......Z........####################',
      '####################..==========....####################',
      '####################..T....H.....T..####################',
      '####################................####################',
      '####################.......^........####################',
      '###########################..###########################',
      '##############............................##############',
      '#c...........#..T......................T..#...........c#',
      '#............#............................#............#',
      '#..T......T..#.....XX..............XX.....#..T......T..#',
      '#............#.....XX.....CCCC.....XX.....#............#',
      '#...=====....#............C..C............#....=====...#',
      '#.....Z.=.................C..C.................=.Z.....#',
      '#...=====....#............CCCC............#....=====...#',
      '#............#............................#............#',
      '#..T......T..#.....XX..............XX.....#..T...H..T..#',
      '#....o.......#.....XX.......>......XX.....#............#',
      '#...........c#............................#c...........#',
      '##############..T......................T..##############',
      '##############............................##############',
      '##############.......g............g.......##############',
      '##############............................##############',
      '##############............................##############',
      '###############.###########..###########.###############',
      '#................#c..................c#................#',
      '#.XX..XX.........#....................#.XX.XX.XX.XX....#',
      '#.XX..XX....L....#...=====....=====...#................#',
      '#...........L....#....................#.XX.XX.XX.XX..o.#',
      '#................#.........<..........#................#',
      '#..P.............#....................#..a......r......#',
      '#.......xx.......#...E..........E.....#.O............L.#',
      '#B..............r#....................#................#',
      '########################################################',
    ],
    briefing: [
      ['snake', 'I am aboard. Gravity is a little light. Smells like a reptile house.'],
      ['threnody', 'WELCOME, SOLDIER. YOU ARE INSIDE THE HOLLOW CHOIR. I AM ITS VOICE, AND ITS PRISONER.'],
      ['threnody', 'THE LULLABY ARRAY DRAWS ON THREE RESONANCE CORES. NORTH. WEST. EAST. BREAK ALL THREE AND THE SONG ENDS.'],
      ['iris', 'I have verified the schematic. Plant a charge on each core with ACT. The detonation will cascade.'],
      ['hale', 'Once they are set you will have under two minutes to reach an escape pod in the south bay. Do not be aboard when it blows.'],
      ['snake', 'Wouldn\'t dream of it.'],
      ['threnody', 'AND WHEN THE SHIP BURNS, LITTLE SISTER, REMEMBER WHO SET YOU FREE.'],
    ],
    allCores: [
      ['iris', 'All three charges are armed! The ship\'s alarm is sounding: every hostile aboard knows you are here.'],
      ['threnody', 'THE SONG IS BREAKING. HOW LOUD. HOW BEAUTIFUL. RUN, SOLDIER.'],
      ['hale', 'Escape pods, south bay. Go, Snake. GO!'],
    ],
  },
];

const ENDING = [
  ['hale', 'Snake! The mothership just lit up like a second sun. The Lullaby Array is gone. The other Vyrr ships are pulling back to high orbit.'],
  ['iris', 'Your pod beacon is strong. Recovery teams are en route to the Pacific splashdown zone.'],
  ['snake', 'What about Threnody?'],
  ['iris', '...Its last transmission is still arriving. Forty thousand pages. Most of it is poetry. Some of it is the location of every other Vyrr ship\'s core.'],
  ['hale', 'Officially, the Accord still stands. Officially, none of this happened.'],
  ['snake', 'Story of my life, Colonel.'],
];

const CAST = {
  snake: { name: 'SNAKE', portrait: 'snake' },
  hale: { name: 'COL. HALE', portrait: 'hale' },
  iris: { name: 'IRIS // AI', portrait: 'iris' },
  threnody: { name: 'THRENODY', portrait: 'threnody' },
};
